### ISSUE TITLE
default_app_config generates warning on Django 3.2+

### ISSUE THREAD

**Issue by markedwards** [reset-button/ariadne_django#27]
The presence of `default_app_config` triggers a warning as of Django 3.2:
```
/usr/local/lib/python3.9/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'ariadne.contrib.django' defines default_app_config = 'ariadne.contrib.django.apps.AriadneConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

Maybe it makes sense to wrap this in a `django.VERSION` check?

**Comment by maxmorlocke** [comment]
Someone got around to upgrading to django 3.2 before us.  Thanks for the report, I'll add this as a feature to the 0.2.0 release.
