### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by chrisapplegate** [reset-button/ariadne_django#46]
I see a couple of changes have been made to the main branch since the last release - the one I was looking for was the change from `simplejson` to `json`. Is it possible to get a new release so I can update my requirements file to this with a numbered version?

I see the project is looking for new maintainers - I may be able to help out on this, if required.

**Comment by Zorig** [comment]
No new release yet?

**Comment by khasbilegt** [comment]
Still nothing?

**Comment by maxmorlocke** [comment]
New release cut
