### ISSUE TITLE
Ariadne 0.14

### ISSUE THREAD

**Issue by bartenra** [reset-button/ariadne_django#48]
Why is the requirement pinned to 0.13? Any blockers?

**Comment by markedwards** [comment]
Seconded.  Why is this pinned?

**Comment by gdalmau** [comment]
Note that the installation via `pip` does not have ariadne pinned to 0.13, you can see it by checking the [`setup.py`](https://github.com/reset-button/ariadne_django/blob/main/setup.py#L35-L38).

```python
install_requires=[
    "django>=2.2.0",
    "ariadne>=0.13.0",
],
```

Also note that this library has some inconsistencies in packaging terms.

**Comment by maxmorlocke** [comment]
Latest release should unpin.
